DROP DATABASE if EXISTS SCIENTIFIC_JOURNALS;
GO

CREATE DATABASE SCIENTIFIC_JOURNALS;
GO

USE master;
GO

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'ZCcGognOT6KQiACu49c9y1TDbHr9Lo7SQjtbqA1zduWxNaUlXg';
CREATE CERTIFICATE SERVERCERT WITH SUBJECT = 'My DEK Certificate';
GO

USE SCIENTIFIC_JOURNALS
GO

CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE SERVERCERT;
GO

ALTER DATABASE SCIENTIFIC_JOURNALS
SET ENCRYPTION ON;
GO