consecutive:
  description: "Consecutive"
  modelName: "Consecutive"
  formName: "consecutiveForm"
  htmlName: "consecutive_form.html"
  foreignKeyMappings:
    - 'table_name_id': 'table_name'
    - 'type_id': 'type'

job:
  description: "Job"
  modelName: "Job"
  formName: "jobForm"
  htmlName: "job_form.html"
  foreignKeyMappings:
    - 'user_role_id': 'user_role'

user-role:
  description: "User Role"
  modelName: "UserRole"
  formName: "userRoleForm"
  htmlName: "user_role_form.html"

degree:
  description: "Degree"
  modelName: "Degree"
  formName: "degreeForm"
  htmlName: "degree_form.html"

code:
  description: "Code"
  modelName: "Code"
  formName: "codeForm"
  htmlName: "code_form.html"

branch:
  description: "Branch"
  modelName: "Branch"
  formName: "branchForm"
  htmlName: "branch_form.html"

project:
  description: "Project"
  modelName: "Project"
  formName: "projectForm"
  htmlName: "project_form.html"
  foreignKeyMappings:
    - 'person_id': 'person'
    - 'branch_id': 'branch'

equipment:
  description: "Equipment"
  modelName: "Equipment"
  formName: "equipmentForm"
  htmlName: "equipment_form.html"
